### ISSUE TITLE
Incompatible with Magma

### ISSUE THREAD

**Issue by hadesTTW** [gegy1000/Terrarium#102]
This is probably a problem on Magma's end and not yours, but I thought I should share it anyways, in case if you have any ideas on how to resolve it. Upon startup on a Magma server, the game crashes. It runs fine on a normal Forge server with Terrarium.
[crash-2020-07-03_12.17.24-server.txt](https://github.com/gegy1000/Terrarium/files/4874159/crash-2020-07-03_12.17.24-server.txt)

``java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:436)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Thread.java:748)``

I opened the issue on Magma's github as well. I hope you have a great day.
https://github.com/magmafoundation/Magma/issues/180

**Comment by wolflord212312** [comment]
yea got the same problem

**Comment by Ashparty** [comment]
Odd, this seams to work on magma for me.

**Comment by ghost** [comment]
same here

**Comment by Gegy** [comment]
This should be resolved in https://github.com/Gegy/Terrarium/commit/bddd0d2b8311b1a253243c5b6769c201728a88b3, I will release 1.1.6 shortly. 🙂

**Comment by hadesTTW** [comment]
Thank you so much! After over an year, I can finally start my modded Earth server now. 💗
