### ISSUE TITLE
Failed to prepare Terrarium for use!

### ISSUE THREAD

**Issue by ireece1** [gegy1000/Terrarium#109]
seems like an issue with the server; I just downloaded 1.1.2 from curseforge

[17:26:46] [Client thread/WARN] [earth]: Failed to prepare Terrarium for use
java.io.FileNotFoundException: https://gist.githubusercontent.com/gegy1000/07de90970dbb502f9b544481e090a081/raw/terrarium_keys.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at java.net.URL.openStream(URL.java:1038) ~[?:1.8.0_51]
	at net.gegy1000.earth.server.shared.ApiKeyInitializer.initialize(ApiKeyInitializer.java:22) ~[ApiKeyInitializer.class:?]
	at net.gegy1000.earth.server.shared.SharedDataInitializers.lambda$initialize$0(SharedDataInitializers.java:44) ~[SharedDataInitializers.class:?]
	at net.gegy1000.earth.server.shared.SharedDataInitializers$$Lambda$4405/233365661.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51]

**Comment by Gegy** [comment]
Oh no, this is exactly what 1.1.2 is supposed to fix

**Comment by Gegy** [comment]
Are you definitely running 1.1.2? That URL doesn't even exist in the jar anymore, so in theory that shouldn't be possible :P

**Comment by ireece1** [comment]
Yes I downloaded it from curse.

I haven’t had Terrarium in my pack in quite awhile; do the previous versions write and reference the URL from the config? If that’s the case then this issue may be solved by deleting the old config. Will check after work

**Comment by Gegy** [comment]
It’s a constant in the code- I’ve double checked through the jar on Curse and the URL doesn’t seem to be there. 😅 If you’re able to send a log over, might be able to find out some stuff

**Comment by ireece1** [comment]
holy fuck curse sent me the 1.1.0 version instead of the 1.1.2 version for some reason.

pop, lock and loaded works fine now
