### ISSUE TITLE
Potential incompatbility with Random Toolkit

### ISSUE THREAD

**Issue by Gegy** [gegy1000/Terrarium#66]
This has been reported to occur when [Random Toolkit](https://github.com/KodyJKing/RandomToolKit) is installed, but not without 
```
java.lang.IllegalStateException: Terrarium chunk generator must implement TerrariumChunkGenerator
    at net.gegy1000.terrarium.server.capability.TerrariumWorldData$Implementation.<init>(TerrariumWorldData.java:53)
    at net.gegy1000.terrarium.server.ServerEventHandler.onAttachWorldCapabilities(ServerEventHandler.java:66)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_236_ServerEventHandler_onAttachWorldCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:656)
    at net.minecraft.world.World.initCapabilities(World.java:3972)
    at net.minecraft.world.WorldServerMulti.func_175643_b(WorldServerMulti.java:79)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:104)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Gegy** [comment]
Got another report of this, more likely seems to be related to SpongeForge wrapping the chunkgenerator.
