### ISSUE TITLE
Crash in the earth customization screen

### ISSUE THREAD

**Issue by SebastianTAPM** [gegy1000/Terrarium#81]
Hello, when im want to create an earth world (with terrarium 1.0.1) it crashes,
this is the crash section of the log:
[12:06:28] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 40 mods
[12:06:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[12:06:29] [main/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[12:06:31] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient]: Could not authorize you against Realms server: Invalid session id
[12:08:28] [main/WARN] [net.minecraft.client.renderer.texture.TextureManager]: Failed to load texture: earth:textures/preset/earth.png
java.io.FileNotFoundException: earth:textures/preset/earth.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at net.gegy1000.terrarium.client.gui.widget.PresetList$PresetEntry.func_192634_a(PresetList.java:109) [PresetList$PresetEntry.class:?]
	at net.minecraft.client.gui.GuiListExtended.func_192637_a(SourceFile:25) [bjm.class:?]
	at net.minecraft.client.gui.GuiSlot.func_192638_a(GuiSlot.java:420) [bjr.class:?]
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:194) [bjr.class:?]
	at net.gegy1000.terrarium.client.gui.customization.SelectPresetGui.func_73863_a(SelectPresetGui.java:59) [SelectPresetGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?]
[12:08:33] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@22b5f2b:
java.lang.NullPointerException: null
	at stellarium.stellars.StellarManager.loadOrCreateManager(StellarManager.java:27) ~[StellarManager.class:?]
	at stellarium.StellarForgeEventHook.preAttachCapabilities(StellarForgeEventHook.java:20) ~[StellarForgeEventHook.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_StellarForgeEventHook_preAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:656) [ForgeEventFactory.class:?]
	at net.minecraft.world.World.initCapabilities(World.java:3972) [amu.class:?]
	at net.gegy1000.terrarium.client.preview.PreviewDummyWorld.<init>(PreviewDummyWorld.java:41) [PreviewDummyWorld.class:?]
	at net.gegy1000.terrarium.client.preview.WorldPreview.<init>(WorldPreview.java:70) [WorldPreview.class:?]
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.rebuildState(TerrariumCustomizationGui.java:259) [TerrariumCustomizationGui.class:?]
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.func_73876_c(TerrariumCustomizationGui.java:166) [TerrariumCustomizationGui.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1778) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?]
[12:08:33] [main/ERROR] [FML]: Index: 2 Listeners:
[12:08:33] [main/ERROR] [FML]: 0: HIGHEST
[12:08:33] [main/ERROR] [FML]: 1: ASM: stellarapi.reference.WorldSets@4b6e1514 attachWorldCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 2: ASM: stellarium.StellarForgeEventHook@38bd2707 preAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 3: NORMAL
[12:08:33] [main/ERROR] [FML]: 4: ASM: class com.tiviacz.travellersbackpack.handlers.PlayerEventHandler attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 5: ASM: class org.orecruncher.dsurround.capabilities.CapabilitySpeechData$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 6: ASM: class org.orecruncher.dsurround.capabilities.CapabilityDimensionInfo$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 7: ASM: class org.orecruncher.dsurround.capabilities.CapabilitySeasonInfo$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 8: ASM: class org.orecruncher.dsurround.capabilities.CapabilityEntityFXData$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 9: ASM: class org.orecruncher.dsurround.capabilities.CapabilityEntityData$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 10: ASM: class net.gegy1000.terrarium.server.ServerEventHandler onAttachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 11: ASM: tt.betterslabsmod.capability.CapabilityHandler@14ce2b1f attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 12: ASM: com.vicmatskiv.weaponlib.ServerEventHandler@59c25d6c attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 13: ASM: stellarapi.reference.SAPIReferenceHandler@301e428b onGatherWorldCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 14: ASM: stellarapi.reference.SAPIReferenceHandler@301e428b onGatherEntityCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 15: ASM: io.github.opencubicchunks.cubicchunks.core.CommonEventHandler@396f13c3 onWorldAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:33] [main/ERROR] [FML]: 16: ASM: blusunrize.immersiveengineering.common.EventHandler@52181747 onCapabilitiesAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[12:08:44] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking screen
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1791) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?]
Caused by: java.lang.NullPointerException
	at stellarium.stellars.StellarManager.loadOrCreateManager(StellarManager.java:27) ~[StellarManager.class:?]
	at stellarium.StellarForgeEventHook.preAttachCapabilities(StellarForgeEventHook.java:20) ~[StellarForgeEventHook.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_StellarForgeEventHook_preAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:656) ~[ForgeEventFactory.class:?]
	at net.minecraft.world.World.initCapabilities(World.java:3972) ~[amu.class:?]
	at net.gegy1000.terrarium.client.preview.PreviewDummyWorld.<init>(PreviewDummyWorld.java:41) ~[PreviewDummyWorld.class:?]
	at net.gegy1000.terrarium.client.preview.WorldPreview.<init>(WorldPreview.java:70) ~[WorldPreview.class:?]
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.rebuildState(TerrariumCustomizationGui.java:259) ~[TerrariumCustomizationGui.class:?]
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.func_73876_c(TerrariumCustomizationGui.java:166) ~[TerrariumCustomizationGui.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1778) ~[bib.class:?]
	... 14 more
[12:08:44] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  B3M_CorePlugin (B3M-1.12.2-15.jar)
  weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 9/23/19 12:08 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at stellarium.stellars.StellarManager.loadOrCreateManager(StellarManager.java:27)
	at stellarium.StellarForgeEventHook.preAttachCapabilities(StellarForgeEventHook.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_StellarForgeEventHook_preAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:656)
	at net.minecraft.world.World.initCapabilities(World.java:3972)
	at net.gegy1000.terrarium.client.preview.PreviewDummyWorld.<init>(PreviewDummyWorld.java:41)
	at net.gegy1000.terrarium.client.preview.WorldPreview.<init>(WorldPreview.java:70)
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.rebuildState(TerrariumCustomizationGui.java:259)
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.func_73876_c(TerrariumCustomizationGui.java:166)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1778)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at stellarium.stellars.StellarManager.loadOrCreateManager(StellarManager.java:27)
	at stellarium.StellarForgeEventHook.preAttachCapabilities(StellarForgeEventHook.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_StellarForgeEventHook_preAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:656)
	at net.minecraft.world.World.initCapabilities(World.java:3972)
	at net.gegy1000.terrarium.client.preview.PreviewDummyWorld.<init>(PreviewDummyWorld.java:41)
	at net.gegy1000.terrarium.client.preview.WorldPreview.<init>(WorldPreview.java:70)
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.rebuildState(TerrariumCustomizationGui.java:259)
	at net.gegy1000.terrarium.client.gui.customization.TerrariumCustomizationGui.func_73876_c(TerrariumCustomizationGui.java:166)

-- Affected screen --
Details:
	Screen name: net.gegy1000.earth.client.gui.EarthCustomizationGui
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1778)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1124678176 bytes (1072 MB) / 3187671040 bytes (3040 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 40 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                   | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                    | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                  | 9.42                      | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                  | 8.0.99.99                 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.5.2768              | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | betterfonts          | 1.9.1                     | minecraft.jar                                 | None                                     |
	| UCHIJA | dsurroundcore        | 3.5.4.3                   | minecraft.jar                                 | None                                     |
	| UCHIJA | securitycraft        | v1.8.12.1                 | [1.12.2]+SecurityCraft+v1.8.12.1.jar          | None                                     |
	| UCHIJA | B3M                  | 1.12.2-15                 | B3M-1.12.2-15.jar                             | None                                     |
	| UCHIJA | basketcase           | 1.0.31                    | Basketcase-v1.0.31-mc1.12.2.jar               | None                                     |
	| UCHIJA | betterslabsmod       | 0.0.7                     | Better+Slabs+Mod+[0.0.7].jar                  | None                                     |
	| UCHIJA | biomesoplenty        | 7.0.1.2441                | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| UCHIJA | zawa                 | 1.12.2-1.6.0              | zawa+-+1.6.0+(1.12.2).jar                     | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJA | bookworm             | 1.12.2-2.3.0              | bookworm-1.12.2-2.3.0.jar                     | None                                     |
	| UCHIJA | cfm                  | 6.3.0                     | cfm-6.3.0-mc1.12.2.jar                        | None                                     |
	| UCHIJA | ctm                  | MC1.12.2-0.3.3.22         | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
	| UCHIJA | chisel               | MC1.12.2-0.2.1.35         | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| UCHIJA | cubicchunks          | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar | None                                     |
	| UCHIJA | dynamictrees         | 1.12.2-0.9.5              | DynamicTrees-1.12.2-0.9.5.jar                 | None                                     |
	| UCHIJA | exoticbirds          | 1.0                       | Exotic+Birds+1.12.2-3.0.0.jar                 | None                                     |
	| UCHIJA | flagged              | 0.1.1                     | flagged-1.12.2-0.1.1.jar                      | None                                     |
	| UCHIJA | trackapi             | 1.1                       | TrackAPI-1.1_1.12.jar                         | None                                     |
	| UCHIJA | immersiveengineering | 0.12-89                   | ImmersiveEngineering-0.12-89.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA | immersiverailroading | 1.6.1                     | ImmersiveRailroading-1.6.1_1.12-1138.jar      | None                                     |
	| UCHIJA | ic2                  | 2.8.187-ex112             | industrialcraft-2-2.8.187-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | mineralogy           | 3.4.0                     | Mineralogy-1.12-3.4.0.29.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | mw                   | 0.4.1                     | mw_2.0-0.4.1_mc1.12.2.jar                     | None                                     |
	| UCHIJA | openablewindows      | 0.0.1                     | openablewindows-1.0.jar                       | None                                     |
	| UCHIJA | petcraft             | 1.0.0                     | PetCraft-Mod-1.12.2.jar                       | None                                     |
	| UCHIJA | rfp2                 | 1.12.2-1.2.2              | RealFirstPerson2-1.12.2-1.2.2.jar             | None                                     |
	| UCHIJA | realdrops            | 1.2.14                    | RealisticItemDrops-1.2.14.jar                 | None                                     |
	| UCHIJA | sereneseasons        | 1.2.16                    | SereneSeasons-1.12.2-1.2.16-universal.jar     | None                                     |
	| UCHIJA | stellarapi           | 1.12.2-0.4.2.9            | Stellar+API-1.12.2-0.4.2.9.jar                | None                                     |
	| UCHIJA | stellarsky           | 1.12.2-0.5.2.8            | Stellar+Sky-1.12.2-0.5.2.8.jar                | None                                     |
	| UCHIJA | travellersbackpack   | 1.0.20.20                 | TravellersBackpack-1.12.2-1.0.20.20.jar       | None                                     |
	| UCHIJA | undergroundbiomes    | 1.3.7                     | UndergroundBiomesConstructs-1.12-1.3.7.jar    | None                                     |
	| UCHIJA | orelib               | 3.5.2.2                   | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | dsurround            | 3.5.4.3                   | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | terrarium            | 1.0.1                     | terrarium-1.0.1.jar                           | None                                     |
	| UCHIJA | earth                | 1.0.0                     | terrarium-1.0.1.jar                           | None                                     |
	| UD     | cubicchunkscore      | @@VERSION@@               | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
B3M_CorePlugin (B3M-1.12.2-15.jar)
  sedridor.B3M.core.B3M_Transformer
weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6373' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 25.20.100.6373, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (Chile)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
[12:08:44] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\sebas\AppData\Roaming\.minecraft\crash-reports\crash-2019-09-23_12.08.44-client.txt
Help me please

**Comment by SebastianTAPM** [comment]
EDIT: Im have 3 gigs assigned to the JVM

**Comment by ghost** [comment]
CubicChunks and Terrarium don't run well together, except on the dev build, which is VERY buggy.

**Comment by Gegy** [comment]
Yeah, Terrarium isn't compatible with Cubic Chunks. It will be in the next release though. Closing in favour of #11  🙂
